//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BigMac.RewardsService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="QWSSoap", Namespace="http://tempuri.org/MMClub/Service")]
    public partial class QWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Rewards_InsertSubmissionOperationCompleted;
        
        private System.Threading.SendOrPostCallback Rewards_SubmissionOperationCompleted;
        
        private System.Threading.SendOrPostCallback Rewards_NewCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback Rewards_ReceiptExistOperationCompleted;
        
        private System.Threading.SendOrPostCallback Rewards_GetDefaultProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback Rewards_GetInvoiceIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback Rewards_GetInvoiceItemIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback Rewards_GetBalanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback Report_AttendanceListTodayExistOperationCompleted;
        
        private System.Threading.SendOrPostCallback Customer_GetCustomerIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback Customer_NotExistOperationCompleted;
        
        private System.Threading.SendOrPostCallback Customer_ExistOperationCompleted;
        
        private System.Threading.SendOrPostCallback Customer_NRICExistOperationCompleted;
        
        private System.Threading.SendOrPostCallback Customer_HPExistOperationCompleted;
        
        private System.Threading.SendOrPostCallback Customer_GetInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Rewards_GetPartnershipByBranchCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback Customer_GetMemberCardNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Customer_UpdateCardNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Branch_GetDetailsByBranchCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback Common_GetGenerateNewIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback Common_GenerateReturnOperationCompleted;
        
        private System.Threading.SendOrPostCallback Common_GenerateReturnSubmitOperationCompleted;
        
        private System.Threading.SendOrPostCallback Common_GetMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback Common_GetModalMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback Common_SendSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback Common_SendEmailOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public QWS() {
            this.Url = global::BigMac.Properties.Settings.Default.BigMac_RewardsService_QWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Rewards_InsertSubmissionCompletedEventHandler Rewards_InsertSubmissionCompleted;
        
        /// <remarks/>
        public event Rewards_SubmissionCompletedEventHandler Rewards_SubmissionCompleted;
        
        /// <remarks/>
        public event Rewards_NewCustomerCompletedEventHandler Rewards_NewCustomerCompleted;
        
        /// <remarks/>
        public event Rewards_ReceiptExistCompletedEventHandler Rewards_ReceiptExistCompleted;
        
        /// <remarks/>
        public event Rewards_GetDefaultProductCompletedEventHandler Rewards_GetDefaultProductCompleted;
        
        /// <remarks/>
        public event Rewards_GetInvoiceIdCompletedEventHandler Rewards_GetInvoiceIdCompleted;
        
        /// <remarks/>
        public event Rewards_GetInvoiceItemIdCompletedEventHandler Rewards_GetInvoiceItemIdCompleted;
        
        /// <remarks/>
        public event Rewards_GetBalanceCompletedEventHandler Rewards_GetBalanceCompleted;
        
        /// <remarks/>
        public event Report_AttendanceListTodayExistCompletedEventHandler Report_AttendanceListTodayExistCompleted;
        
        /// <remarks/>
        public event Customer_GetCustomerIDCompletedEventHandler Customer_GetCustomerIDCompleted;
        
        /// <remarks/>
        public event Customer_NotExistCompletedEventHandler Customer_NotExistCompleted;
        
        /// <remarks/>
        public event Customer_ExistCompletedEventHandler Customer_ExistCompleted;
        
        /// <remarks/>
        public event Customer_NRICExistCompletedEventHandler Customer_NRICExistCompleted;
        
        /// <remarks/>
        public event Customer_HPExistCompletedEventHandler Customer_HPExistCompleted;
        
        /// <remarks/>
        public event Customer_GetInfoCompletedEventHandler Customer_GetInfoCompleted;
        
        /// <remarks/>
        public event Rewards_GetPartnershipByBranchCodeCompletedEventHandler Rewards_GetPartnershipByBranchCodeCompleted;
        
        /// <remarks/>
        public event Customer_GetMemberCardNoCompletedEventHandler Customer_GetMemberCardNoCompleted;
        
        /// <remarks/>
        public event Customer_UpdateCardNoCompletedEventHandler Customer_UpdateCardNoCompleted;
        
        /// <remarks/>
        public event Branch_GetDetailsByBranchCodeCompletedEventHandler Branch_GetDetailsByBranchCodeCompleted;
        
        /// <remarks/>
        public event Common_GetGenerateNewIDCompletedEventHandler Common_GetGenerateNewIDCompleted;
        
        /// <remarks/>
        public event Common_GenerateReturnCompletedEventHandler Common_GenerateReturnCompleted;
        
        /// <remarks/>
        public event Common_GenerateReturnSubmitCompletedEventHandler Common_GenerateReturnSubmitCompleted;
        
        /// <remarks/>
        public event Common_GetMessageCompletedEventHandler Common_GetMessageCompleted;
        
        /// <remarks/>
        public event Common_GetModalMessageCompletedEventHandler Common_GetModalMessageCompleted;
        
        /// <remarks/>
        public event Common_SendSMSCompletedEventHandler Common_SendSMSCompleted;
        
        /// <remarks/>
        public event Common_SendEmailCompletedEventHandler Common_SendEmailCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MMClub/Service/Rewards_InsertSubmission", RequestNamespace="http://tempuri.org/MMClub/Service", ResponseNamespace="http://tempuri.org/MMClub/Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Rewards_InsertSubmission(string name, string mobile, string email, string nric, string dateofbirth, string receiptno, string gender, decimal amount, string branchcode, string createid) {
            object[] results = this.Invoke("Rewards_InsertSubmission", new object[] {
                        name,
                        mobile,
                        email,
                        nric,
                        dateofbirth,
                        receiptno,
                        gender,
                        amount,
                        branchcode,
                        createid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Rewards_InsertSubmissionAsync(string name, string mobile, string email, string nric, string dateofbirth, string receiptno, string gender, decimal amount, string branchcode, string createid) {
            this.Rewards_InsertSubmissionAsync(name, mobile, email, nric, dateofbirth, receiptno, gender, amount, branchcode, createid, null);
        }
        
        /// <remarks/>
        public void Rewards_InsertSubmissionAsync(string name, string mobile, string email, string nric, string dateofbirth, string receiptno, string gender, decimal amount, string branchcode, string createid, object userState) {
            if ((this.Rewards_InsertSubmissionOperationCompleted == null)) {
                this.Rewards_InsertSubmissionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRewards_InsertSubmissionOperationCompleted);
            }
            this.InvokeAsync("Rewards_InsertSubmission", new object[] {
                        name,
                        mobile,
                        email,
                        nric,
                        dateofbirth,
                        receiptno,
                        gender,
                        amount,
                        branchcode,
                        createid}, this.Rewards_InsertSubmissionOperationCompleted, userState);
        }
        
        private void OnRewards_InsertSubmissionOperationCompleted(object arg) {
            if ((this.Rewards_InsertSubmissionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Rewards_InsertSubmissionCompleted(this, new Rewards_InsertSubmissionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MMClub/Service/Rewards_Submission", RequestNamespace="http://tempuri.org/MMClub/Service", ResponseNamespace="http://tempuri.org/MMClub/Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Rewards_Submission(string name, string mobile, string email, string nric, string dateofbirth, string receiptno, string gender, decimal amount, string branchcode, string createid) {
            object[] results = this.Invoke("Rewards_Submission", new object[] {
                        name,
                        mobile,
                        email,
                        nric,
                        dateofbirth,
                        receiptno,
                        gender,
                        amount,
                        branchcode,
                        createid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Rewards_SubmissionAsync(string name, string mobile, string email, string nric, string dateofbirth, string receiptno, string gender, decimal amount, string branchcode, string createid) {
            this.Rewards_SubmissionAsync(name, mobile, email, nric, dateofbirth, receiptno, gender, amount, branchcode, createid, null);
        }
        
        /// <remarks/>
        public void Rewards_SubmissionAsync(string name, string mobile, string email, string nric, string dateofbirth, string receiptno, string gender, decimal amount, string branchcode, string createid, object userState) {
            if ((this.Rewards_SubmissionOperationCompleted == null)) {
                this.Rewards_SubmissionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRewards_SubmissionOperationCompleted);
            }
            this.InvokeAsync("Rewards_Submission", new object[] {
                        name,
                        mobile,
                        email,
                        nric,
                        dateofbirth,
                        receiptno,
                        gender,
                        amount,
                        branchcode,
                        createid}, this.Rewards_SubmissionOperationCompleted, userState);
        }
        
        private void OnRewards_SubmissionOperationCompleted(object arg) {
            if ((this.Rewards_SubmissionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Rewards_SubmissionCompleted(this, new Rewards_SubmissionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MMClub/Service/Rewards_NewCustomer", RequestNamespace="http://tempuri.org/MMClub/Service", ResponseNamespace="http://tempuri.org/MMClub/Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Rewards_NewCustomer(string name, string mobile, string email, string nric, string dateofbirth, string gender, string branchcode, string createid) {
            object[] results = this.Invoke("Rewards_NewCustomer", new object[] {
                        name,
                        mobile,
                        email,
                        nric,
                        dateofbirth,
                        gender,
                        branchcode,
                        createid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Rewards_NewCustomerAsync(string name, string mobile, string email, string nric, string dateofbirth, string gender, string branchcode, string createid) {
            this.Rewards_NewCustomerAsync(name, mobile, email, nric, dateofbirth, gender, branchcode, createid, null);
        }
        
        /// <remarks/>
        public void Rewards_NewCustomerAsync(string name, string mobile, string email, string nric, string dateofbirth, string gender, string branchcode, string createid, object userState) {
            if ((this.Rewards_NewCustomerOperationCompleted == null)) {
                this.Rewards_NewCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRewards_NewCustomerOperationCompleted);
            }
            this.InvokeAsync("Rewards_NewCustomer", new object[] {
                        name,
                        mobile,
                        email,
                        nric,
                        dateofbirth,
                        gender,
                        branchcode,
                        createid}, this.Rewards_NewCustomerOperationCompleted, userState);
        }
        
        private void OnRewards_NewCustomerOperationCompleted(object arg) {
            if ((this.Rewards_NewCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Rewards_NewCustomerCompleted(this, new Rewards_NewCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MMClub/Service/Rewards_ReceiptExist", RequestNamespace="http://tempuri.org/MMClub/Service", ResponseNamespace="http://tempuri.org/MMClub/Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Rewards_ReceiptExist(string receiptno) {
            object[] results = this.Invoke("Rewards_ReceiptExist", new object[] {
                        receiptno});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Rewards_ReceiptExistAsync(string receiptno) {
            this.Rewards_ReceiptExistAsync(receiptno, null);
        }
        
        /// <remarks/>
        public void Rewards_ReceiptExistAsync(string receiptno, object userState) {
            if ((this.Rewards_ReceiptExistOperationCompleted == null)) {
                this.Rewards_ReceiptExistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRewards_ReceiptExistOperationCompleted);
            }
            this.InvokeAsync("Rewards_ReceiptExist", new object[] {
                        receiptno}, this.Rewards_ReceiptExistOperationCompleted, userState);
        }
        
        private void OnRewards_ReceiptExistOperationCompleted(object arg) {
            if ((this.Rewards_ReceiptExistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Rewards_ReceiptExistCompleted(this, new Rewards_ReceiptExistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MMClub/Service/Rewards_GetDefaultProduct", RequestNamespace="http://tempuri.org/MMClub/Service", ResponseNamespace="http://tempuri.org/MMClub/Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Rewards_GetDefaultProduct() {
            object[] results = this.Invoke("Rewards_GetDefaultProduct", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Rewards_GetDefaultProductAsync() {
            this.Rewards_GetDefaultProductAsync(null);
        }
        
        /// <remarks/>
        public void Rewards_GetDefaultProductAsync(object userState) {
            if ((this.Rewards_GetDefaultProductOperationCompleted == null)) {
                this.Rewards_GetDefaultProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRewards_GetDefaultProductOperationCompleted);
            }
            this.InvokeAsync("Rewards_GetDefaultProduct", new object[0], this.Rewards_GetDefaultProductOperationCompleted, userState);
        }
        
        private void OnRewards_GetDefaultProductOperationCompleted(object arg) {
            if ((this.Rewards_GetDefaultProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Rewards_GetDefaultProductCompleted(this, new Rewards_GetDefaultProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MMClub/Service/Rewards_GetInvoiceId", RequestNamespace="http://tempuri.org/MMClub/Service", ResponseNamespace="http://tempuri.org/MMClub/Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Rewards_GetInvoiceId(string resourcecode) {
            object[] results = this.Invoke("Rewards_GetInvoiceId", new object[] {
                        resourcecode});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Rewards_GetInvoiceIdAsync(string resourcecode) {
            this.Rewards_GetInvoiceIdAsync(resourcecode, null);
        }
        
        /// <remarks/>
        public void Rewards_GetInvoiceIdAsync(string resourcecode, object userState) {
            if ((this.Rewards_GetInvoiceIdOperationCompleted == null)) {
                this.Rewards_GetInvoiceIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRewards_GetInvoiceIdOperationCompleted);
            }
            this.InvokeAsync("Rewards_GetInvoiceId", new object[] {
                        resourcecode}, this.Rewards_GetInvoiceIdOperationCompleted, userState);
        }
        
        private void OnRewards_GetInvoiceIdOperationCompleted(object arg) {
            if ((this.Rewards_GetInvoiceIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Rewards_GetInvoiceIdCompleted(this, new Rewards_GetInvoiceIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MMClub/Service/Rewards_GetInvoiceItemId", RequestNamespace="http://tempuri.org/MMClub/Service", ResponseNamespace="http://tempuri.org/MMClub/Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Rewards_GetInvoiceItemId(string resourcecode) {
            object[] results = this.Invoke("Rewards_GetInvoiceItemId", new object[] {
                        resourcecode});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Rewards_GetInvoiceItemIdAsync(string resourcecode) {
            this.Rewards_GetInvoiceItemIdAsync(resourcecode, null);
        }
        
        /// <remarks/>
        public void Rewards_GetInvoiceItemIdAsync(string resourcecode, object userState) {
            if ((this.Rewards_GetInvoiceItemIdOperationCompleted == null)) {
                this.Rewards_GetInvoiceItemIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRewards_GetInvoiceItemIdOperationCompleted);
            }
            this.InvokeAsync("Rewards_GetInvoiceItemId", new object[] {
                        resourcecode}, this.Rewards_GetInvoiceItemIdOperationCompleted, userState);
        }
        
        private void OnRewards_GetInvoiceItemIdOperationCompleted(object arg) {
            if ((this.Rewards_GetInvoiceItemIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Rewards_GetInvoiceItemIdCompleted(this, new Rewards_GetInvoiceItemIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MMClub/Service/Rewards_GetBalance", RequestNamespace="http://tempuri.org/MMClub/Service", ResponseNamespace="http://tempuri.org/MMClub/Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Rewards_GetBalance(int intcussupid, string redemptiontype) {
            object[] results = this.Invoke("Rewards_GetBalance", new object[] {
                        intcussupid,
                        redemptiontype});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Rewards_GetBalanceAsync(int intcussupid, string redemptiontype) {
            this.Rewards_GetBalanceAsync(intcussupid, redemptiontype, null);
        }
        
        /// <remarks/>
        public void Rewards_GetBalanceAsync(int intcussupid, string redemptiontype, object userState) {
            if ((this.Rewards_GetBalanceOperationCompleted == null)) {
                this.Rewards_GetBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRewards_GetBalanceOperationCompleted);
            }
            this.InvokeAsync("Rewards_GetBalance", new object[] {
                        intcussupid,
                        redemptiontype}, this.Rewards_GetBalanceOperationCompleted, userState);
        }
        
        private void OnRewards_GetBalanceOperationCompleted(object arg) {
            if ((this.Rewards_GetBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Rewards_GetBalanceCompleted(this, new Rewards_GetBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MMClub/Service/Report_AttendanceListTodayExist", RequestNamespace="http://tempuri.org/MMClub/Service", ResponseNamespace="http://tempuri.org/MMClub/Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Report_AttendanceListTodayExist() {
            object[] results = this.Invoke("Report_AttendanceListTodayExist", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Report_AttendanceListTodayExistAsync() {
            this.Report_AttendanceListTodayExistAsync(null);
        }
        
        /// <remarks/>
        public void Report_AttendanceListTodayExistAsync(object userState) {
            if ((this.Report_AttendanceListTodayExistOperationCompleted == null)) {
                this.Report_AttendanceListTodayExistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReport_AttendanceListTodayExistOperationCompleted);
            }
            this.InvokeAsync("Report_AttendanceListTodayExist", new object[0], this.Report_AttendanceListTodayExistOperationCompleted, userState);
        }
        
        private void OnReport_AttendanceListTodayExistOperationCompleted(object arg) {
            if ((this.Report_AttendanceListTodayExistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Report_AttendanceListTodayExistCompleted(this, new Report_AttendanceListTodayExistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MMClub/Service/Customer_GetCustomerID", RequestNamespace="http://tempuri.org/MMClub/Service", ResponseNamespace="http://tempuri.org/MMClub/Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Customer_GetCustomerID(string inhousecode) {
            object[] results = this.Invoke("Customer_GetCustomerID", new object[] {
                        inhousecode});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Customer_GetCustomerIDAsync(string inhousecode) {
            this.Customer_GetCustomerIDAsync(inhousecode, null);
        }
        
        /// <remarks/>
        public void Customer_GetCustomerIDAsync(string inhousecode, object userState) {
            if ((this.Customer_GetCustomerIDOperationCompleted == null)) {
                this.Customer_GetCustomerIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCustomer_GetCustomerIDOperationCompleted);
            }
            this.InvokeAsync("Customer_GetCustomerID", new object[] {
                        inhousecode}, this.Customer_GetCustomerIDOperationCompleted, userState);
        }
        
        private void OnCustomer_GetCustomerIDOperationCompleted(object arg) {
            if ((this.Customer_GetCustomerIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Customer_GetCustomerIDCompleted(this, new Customer_GetCustomerIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MMClub/Service/Customer_NotExist", RequestNamespace="http://tempuri.org/MMClub/Service", ResponseNamespace="http://tempuri.org/MMClub/Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Customer_NotExist(string nric, string mobileno) {
            object[] results = this.Invoke("Customer_NotExist", new object[] {
                        nric,
                        mobileno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Customer_NotExistAsync(string nric, string mobileno) {
            this.Customer_NotExistAsync(nric, mobileno, null);
        }
        
        /// <remarks/>
        public void Customer_NotExistAsync(string nric, string mobileno, object userState) {
            if ((this.Customer_NotExistOperationCompleted == null)) {
                this.Customer_NotExistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCustomer_NotExistOperationCompleted);
            }
            this.InvokeAsync("Customer_NotExist", new object[] {
                        nric,
                        mobileno}, this.Customer_NotExistOperationCompleted, userState);
        }
        
        private void OnCustomer_NotExistOperationCompleted(object arg) {
            if ((this.Customer_NotExistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Customer_NotExistCompleted(this, new Customer_NotExistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MMClub/Service/Customer_Exist", RequestNamespace="http://tempuri.org/MMClub/Service", ResponseNamespace="http://tempuri.org/MMClub/Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Customer_Exist(string nric, string mobileno) {
            object[] results = this.Invoke("Customer_Exist", new object[] {
                        nric,
                        mobileno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Customer_ExistAsync(string nric, string mobileno) {
            this.Customer_ExistAsync(nric, mobileno, null);
        }
        
        /// <remarks/>
        public void Customer_ExistAsync(string nric, string mobileno, object userState) {
            if ((this.Customer_ExistOperationCompleted == null)) {
                this.Customer_ExistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCustomer_ExistOperationCompleted);
            }
            this.InvokeAsync("Customer_Exist", new object[] {
                        nric,
                        mobileno}, this.Customer_ExistOperationCompleted, userState);
        }
        
        private void OnCustomer_ExistOperationCompleted(object arg) {
            if ((this.Customer_ExistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Customer_ExistCompleted(this, new Customer_ExistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MMClub/Service/Customer_NRICExist", RequestNamespace="http://tempuri.org/MMClub/Service", ResponseNamespace="http://tempuri.org/MMClub/Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Customer_NRICExist(string nric) {
            object[] results = this.Invoke("Customer_NRICExist", new object[] {
                        nric});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Customer_NRICExistAsync(string nric) {
            this.Customer_NRICExistAsync(nric, null);
        }
        
        /// <remarks/>
        public void Customer_NRICExistAsync(string nric, object userState) {
            if ((this.Customer_NRICExistOperationCompleted == null)) {
                this.Customer_NRICExistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCustomer_NRICExistOperationCompleted);
            }
            this.InvokeAsync("Customer_NRICExist", new object[] {
                        nric}, this.Customer_NRICExistOperationCompleted, userState);
        }
        
        private void OnCustomer_NRICExistOperationCompleted(object arg) {
            if ((this.Customer_NRICExistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Customer_NRICExistCompleted(this, new Customer_NRICExistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MMClub/Service/Customer_HPExist", RequestNamespace="http://tempuri.org/MMClub/Service", ResponseNamespace="http://tempuri.org/MMClub/Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Customer_HPExist(string mobileno) {
            object[] results = this.Invoke("Customer_HPExist", new object[] {
                        mobileno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Customer_HPExistAsync(string mobileno) {
            this.Customer_HPExistAsync(mobileno, null);
        }
        
        /// <remarks/>
        public void Customer_HPExistAsync(string mobileno, object userState) {
            if ((this.Customer_HPExistOperationCompleted == null)) {
                this.Customer_HPExistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCustomer_HPExistOperationCompleted);
            }
            this.InvokeAsync("Customer_HPExist", new object[] {
                        mobileno}, this.Customer_HPExistOperationCompleted, userState);
        }
        
        private void OnCustomer_HPExistOperationCompleted(object arg) {
            if ((this.Customer_HPExistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Customer_HPExistCompleted(this, new Customer_HPExistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MMClub/Service/Customer_GetInfo", RequestNamespace="http://tempuri.org/MMClub/Service", ResponseNamespace="http://tempuri.org/MMClub/Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Customer_GetInfo(string nric, string mobileno) {
            object[] results = this.Invoke("Customer_GetInfo", new object[] {
                        nric,
                        mobileno});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Customer_GetInfoAsync(string nric, string mobileno) {
            this.Customer_GetInfoAsync(nric, mobileno, null);
        }
        
        /// <remarks/>
        public void Customer_GetInfoAsync(string nric, string mobileno, object userState) {
            if ((this.Customer_GetInfoOperationCompleted == null)) {
                this.Customer_GetInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCustomer_GetInfoOperationCompleted);
            }
            this.InvokeAsync("Customer_GetInfo", new object[] {
                        nric,
                        mobileno}, this.Customer_GetInfoOperationCompleted, userState);
        }
        
        private void OnCustomer_GetInfoOperationCompleted(object arg) {
            if ((this.Customer_GetInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Customer_GetInfoCompleted(this, new Customer_GetInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MMClub/Service/Rewards_GetPartnershipByBranchCode", RequestNamespace="http://tempuri.org/MMClub/Service", ResponseNamespace="http://tempuri.org/MMClub/Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Rewards_GetPartnershipByBranchCode(string branchcode) {
            object[] results = this.Invoke("Rewards_GetPartnershipByBranchCode", new object[] {
                        branchcode});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Rewards_GetPartnershipByBranchCodeAsync(string branchcode) {
            this.Rewards_GetPartnershipByBranchCodeAsync(branchcode, null);
        }
        
        /// <remarks/>
        public void Rewards_GetPartnershipByBranchCodeAsync(string branchcode, object userState) {
            if ((this.Rewards_GetPartnershipByBranchCodeOperationCompleted == null)) {
                this.Rewards_GetPartnershipByBranchCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRewards_GetPartnershipByBranchCodeOperationCompleted);
            }
            this.InvokeAsync("Rewards_GetPartnershipByBranchCode", new object[] {
                        branchcode}, this.Rewards_GetPartnershipByBranchCodeOperationCompleted, userState);
        }
        
        private void OnRewards_GetPartnershipByBranchCodeOperationCompleted(object arg) {
            if ((this.Rewards_GetPartnershipByBranchCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Rewards_GetPartnershipByBranchCodeCompleted(this, new Rewards_GetPartnershipByBranchCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MMClub/Service/Customer_GetMemberCardNo", RequestNamespace="http://tempuri.org/MMClub/Service", ResponseNamespace="http://tempuri.org/MMClub/Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Customer_GetMemberCardNo() {
            object[] results = this.Invoke("Customer_GetMemberCardNo", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Customer_GetMemberCardNoAsync() {
            this.Customer_GetMemberCardNoAsync(null);
        }
        
        /// <remarks/>
        public void Customer_GetMemberCardNoAsync(object userState) {
            if ((this.Customer_GetMemberCardNoOperationCompleted == null)) {
                this.Customer_GetMemberCardNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCustomer_GetMemberCardNoOperationCompleted);
            }
            this.InvokeAsync("Customer_GetMemberCardNo", new object[0], this.Customer_GetMemberCardNoOperationCompleted, userState);
        }
        
        private void OnCustomer_GetMemberCardNoOperationCompleted(object arg) {
            if ((this.Customer_GetMemberCardNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Customer_GetMemberCardNoCompleted(this, new Customer_GetMemberCardNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MMClub/Service/Customer_UpdateCardNo", RequestNamespace="http://tempuri.org/MMClub/Service", ResponseNamespace="http://tempuri.org/MMClub/Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Customer_UpdateCardNo(string cardno) {
            object[] results = this.Invoke("Customer_UpdateCardNo", new object[] {
                        cardno});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Customer_UpdateCardNoAsync(string cardno) {
            this.Customer_UpdateCardNoAsync(cardno, null);
        }
        
        /// <remarks/>
        public void Customer_UpdateCardNoAsync(string cardno, object userState) {
            if ((this.Customer_UpdateCardNoOperationCompleted == null)) {
                this.Customer_UpdateCardNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCustomer_UpdateCardNoOperationCompleted);
            }
            this.InvokeAsync("Customer_UpdateCardNo", new object[] {
                        cardno}, this.Customer_UpdateCardNoOperationCompleted, userState);
        }
        
        private void OnCustomer_UpdateCardNoOperationCompleted(object arg) {
            if ((this.Customer_UpdateCardNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Customer_UpdateCardNoCompleted(this, new Customer_UpdateCardNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MMClub/Service/Branch_GetDetailsByBranchCode", RequestNamespace="http://tempuri.org/MMClub/Service", ResponseNamespace="http://tempuri.org/MMClub/Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Branch_GetDetailsByBranchCode(string branchcode) {
            object[] results = this.Invoke("Branch_GetDetailsByBranchCode", new object[] {
                        branchcode});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Branch_GetDetailsByBranchCodeAsync(string branchcode) {
            this.Branch_GetDetailsByBranchCodeAsync(branchcode, null);
        }
        
        /// <remarks/>
        public void Branch_GetDetailsByBranchCodeAsync(string branchcode, object userState) {
            if ((this.Branch_GetDetailsByBranchCodeOperationCompleted == null)) {
                this.Branch_GetDetailsByBranchCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBranch_GetDetailsByBranchCodeOperationCompleted);
            }
            this.InvokeAsync("Branch_GetDetailsByBranchCode", new object[] {
                        branchcode}, this.Branch_GetDetailsByBranchCodeOperationCompleted, userState);
        }
        
        private void OnBranch_GetDetailsByBranchCodeOperationCompleted(object arg) {
            if ((this.Branch_GetDetailsByBranchCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Branch_GetDetailsByBranchCodeCompleted(this, new Branch_GetDetailsByBranchCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MMClub/Service/Common_GetGenerateNewID", RequestNamespace="http://tempuri.org/MMClub/Service", ResponseNamespace="http://tempuri.org/MMClub/Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Common_GetGenerateNewID(string tblname, string colname, string prekeyvalue, string startnokeyvalue) {
            object[] results = this.Invoke("Common_GetGenerateNewID", new object[] {
                        tblname,
                        colname,
                        prekeyvalue,
                        startnokeyvalue});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Common_GetGenerateNewIDAsync(string tblname, string colname, string prekeyvalue, string startnokeyvalue) {
            this.Common_GetGenerateNewIDAsync(tblname, colname, prekeyvalue, startnokeyvalue, null);
        }
        
        /// <remarks/>
        public void Common_GetGenerateNewIDAsync(string tblname, string colname, string prekeyvalue, string startnokeyvalue, object userState) {
            if ((this.Common_GetGenerateNewIDOperationCompleted == null)) {
                this.Common_GetGenerateNewIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCommon_GetGenerateNewIDOperationCompleted);
            }
            this.InvokeAsync("Common_GetGenerateNewID", new object[] {
                        tblname,
                        colname,
                        prekeyvalue,
                        startnokeyvalue}, this.Common_GetGenerateNewIDOperationCompleted, userState);
        }
        
        private void OnCommon_GetGenerateNewIDOperationCompleted(object arg) {
            if ((this.Common_GetGenerateNewIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Common_GetGenerateNewIDCompleted(this, new Common_GetGenerateNewIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MMClub/Service/Common_GenerateReturn", RequestNamespace="http://tempuri.org/MMClub/Service", ResponseNamespace="http://tempuri.org/MMClub/Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Common_GenerateReturn(string status, string message) {
            object[] results = this.Invoke("Common_GenerateReturn", new object[] {
                        status,
                        message});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Common_GenerateReturnAsync(string status, string message) {
            this.Common_GenerateReturnAsync(status, message, null);
        }
        
        /// <remarks/>
        public void Common_GenerateReturnAsync(string status, string message, object userState) {
            if ((this.Common_GenerateReturnOperationCompleted == null)) {
                this.Common_GenerateReturnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCommon_GenerateReturnOperationCompleted);
            }
            this.InvokeAsync("Common_GenerateReturn", new object[] {
                        status,
                        message}, this.Common_GenerateReturnOperationCompleted, userState);
        }
        
        private void OnCommon_GenerateReturnOperationCompleted(object arg) {
            if ((this.Common_GenerateReturnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Common_GenerateReturnCompleted(this, new Common_GenerateReturnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MMClub/Service/Common_GenerateReturnSubmit", RequestNamespace="http://tempuri.org/MMClub/Service", ResponseNamespace="http://tempuri.org/MMClub/Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Common_GenerateReturnSubmit(string status, string message, string refno, string outlet, string awardbonus, string balance, string smsdown) {
            object[] results = this.Invoke("Common_GenerateReturnSubmit", new object[] {
                        status,
                        message,
                        refno,
                        outlet,
                        awardbonus,
                        balance,
                        smsdown});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Common_GenerateReturnSubmitAsync(string status, string message, string refno, string outlet, string awardbonus, string balance, string smsdown) {
            this.Common_GenerateReturnSubmitAsync(status, message, refno, outlet, awardbonus, balance, smsdown, null);
        }
        
        /// <remarks/>
        public void Common_GenerateReturnSubmitAsync(string status, string message, string refno, string outlet, string awardbonus, string balance, string smsdown, object userState) {
            if ((this.Common_GenerateReturnSubmitOperationCompleted == null)) {
                this.Common_GenerateReturnSubmitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCommon_GenerateReturnSubmitOperationCompleted);
            }
            this.InvokeAsync("Common_GenerateReturnSubmit", new object[] {
                        status,
                        message,
                        refno,
                        outlet,
                        awardbonus,
                        balance,
                        smsdown}, this.Common_GenerateReturnSubmitOperationCompleted, userState);
        }
        
        private void OnCommon_GenerateReturnSubmitOperationCompleted(object arg) {
            if ((this.Common_GenerateReturnSubmitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Common_GenerateReturnSubmitCompleted(this, new Common_GenerateReturnSubmitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MMClub/Service/Common_GetMessage", RequestNamespace="http://tempuri.org/MMClub/Service", ResponseNamespace="http://tempuri.org/MMClub/Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Common_GetMessage(string messagecode) {
            object[] results = this.Invoke("Common_GetMessage", new object[] {
                        messagecode});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Common_GetMessageAsync(string messagecode) {
            this.Common_GetMessageAsync(messagecode, null);
        }
        
        /// <remarks/>
        public void Common_GetMessageAsync(string messagecode, object userState) {
            if ((this.Common_GetMessageOperationCompleted == null)) {
                this.Common_GetMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCommon_GetMessageOperationCompleted);
            }
            this.InvokeAsync("Common_GetMessage", new object[] {
                        messagecode}, this.Common_GetMessageOperationCompleted, userState);
        }
        
        private void OnCommon_GetMessageOperationCompleted(object arg) {
            if ((this.Common_GetMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Common_GetMessageCompleted(this, new Common_GetMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MMClub/Service/Common_GetModalMessage", RequestNamespace="http://tempuri.org/MMClub/Service", ResponseNamespace="http://tempuri.org/MMClub/Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Common_GetModalMessage(string messagecode, string textToBeReplaced) {
            object[] results = this.Invoke("Common_GetModalMessage", new object[] {
                        messagecode,
                        textToBeReplaced});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Common_GetModalMessageAsync(string messagecode, string textToBeReplaced) {
            this.Common_GetModalMessageAsync(messagecode, textToBeReplaced, null);
        }
        
        /// <remarks/>
        public void Common_GetModalMessageAsync(string messagecode, string textToBeReplaced, object userState) {
            if ((this.Common_GetModalMessageOperationCompleted == null)) {
                this.Common_GetModalMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCommon_GetModalMessageOperationCompleted);
            }
            this.InvokeAsync("Common_GetModalMessage", new object[] {
                        messagecode,
                        textToBeReplaced}, this.Common_GetModalMessageOperationCompleted, userState);
        }
        
        private void OnCommon_GetModalMessageOperationCompleted(object arg) {
            if ((this.Common_GetModalMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Common_GetModalMessageCompleted(this, new Common_GetModalMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MMClub/Service/Common_SendSMS", RequestNamespace="http://tempuri.org/MMClub/Service", ResponseNamespace="http://tempuri.org/MMClub/Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Common_SendSMS(string messagecode, string mobile, string textToBeReplaced) {
            this.Invoke("Common_SendSMS", new object[] {
                        messagecode,
                        mobile,
                        textToBeReplaced});
        }
        
        /// <remarks/>
        public void Common_SendSMSAsync(string messagecode, string mobile, string textToBeReplaced) {
            this.Common_SendSMSAsync(messagecode, mobile, textToBeReplaced, null);
        }
        
        /// <remarks/>
        public void Common_SendSMSAsync(string messagecode, string mobile, string textToBeReplaced, object userState) {
            if ((this.Common_SendSMSOperationCompleted == null)) {
                this.Common_SendSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCommon_SendSMSOperationCompleted);
            }
            this.InvokeAsync("Common_SendSMS", new object[] {
                        messagecode,
                        mobile,
                        textToBeReplaced}, this.Common_SendSMSOperationCompleted, userState);
        }
        
        private void OnCommon_SendSMSOperationCompleted(object arg) {
            if ((this.Common_SendSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Common_SendSMSCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MMClub/Service/Common_SendEmail", RequestNamespace="http://tempuri.org/MMClub/Service", ResponseNamespace="http://tempuri.org/MMClub/Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Common_SendEmail(string messagecode, string toEmail, string textToBeReplaced) {
            this.Invoke("Common_SendEmail", new object[] {
                        messagecode,
                        toEmail,
                        textToBeReplaced});
        }
        
        /// <remarks/>
        public void Common_SendEmailAsync(string messagecode, string toEmail, string textToBeReplaced) {
            this.Common_SendEmailAsync(messagecode, toEmail, textToBeReplaced, null);
        }
        
        /// <remarks/>
        public void Common_SendEmailAsync(string messagecode, string toEmail, string textToBeReplaced, object userState) {
            if ((this.Common_SendEmailOperationCompleted == null)) {
                this.Common_SendEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCommon_SendEmailOperationCompleted);
            }
            this.InvokeAsync("Common_SendEmail", new object[] {
                        messagecode,
                        toEmail,
                        textToBeReplaced}, this.Common_SendEmailOperationCompleted, userState);
        }
        
        private void OnCommon_SendEmailOperationCompleted(object arg) {
            if ((this.Common_SendEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Common_SendEmailCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Rewards_InsertSubmissionCompletedEventHandler(object sender, Rewards_InsertSubmissionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Rewards_InsertSubmissionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Rewards_InsertSubmissionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Rewards_SubmissionCompletedEventHandler(object sender, Rewards_SubmissionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Rewards_SubmissionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Rewards_SubmissionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Rewards_NewCustomerCompletedEventHandler(object sender, Rewards_NewCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Rewards_NewCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Rewards_NewCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Rewards_ReceiptExistCompletedEventHandler(object sender, Rewards_ReceiptExistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Rewards_ReceiptExistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Rewards_ReceiptExistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Rewards_GetDefaultProductCompletedEventHandler(object sender, Rewards_GetDefaultProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Rewards_GetDefaultProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Rewards_GetDefaultProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Rewards_GetInvoiceIdCompletedEventHandler(object sender, Rewards_GetInvoiceIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Rewards_GetInvoiceIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Rewards_GetInvoiceIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Rewards_GetInvoiceItemIdCompletedEventHandler(object sender, Rewards_GetInvoiceItemIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Rewards_GetInvoiceItemIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Rewards_GetInvoiceItemIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Rewards_GetBalanceCompletedEventHandler(object sender, Rewards_GetBalanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Rewards_GetBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Rewards_GetBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Report_AttendanceListTodayExistCompletedEventHandler(object sender, Report_AttendanceListTodayExistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Report_AttendanceListTodayExistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Report_AttendanceListTodayExistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Customer_GetCustomerIDCompletedEventHandler(object sender, Customer_GetCustomerIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Customer_GetCustomerIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Customer_GetCustomerIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Customer_NotExistCompletedEventHandler(object sender, Customer_NotExistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Customer_NotExistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Customer_NotExistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Customer_ExistCompletedEventHandler(object sender, Customer_ExistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Customer_ExistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Customer_ExistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Customer_NRICExistCompletedEventHandler(object sender, Customer_NRICExistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Customer_NRICExistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Customer_NRICExistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Customer_HPExistCompletedEventHandler(object sender, Customer_HPExistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Customer_HPExistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Customer_HPExistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Customer_GetInfoCompletedEventHandler(object sender, Customer_GetInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Customer_GetInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Customer_GetInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Rewards_GetPartnershipByBranchCodeCompletedEventHandler(object sender, Rewards_GetPartnershipByBranchCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Rewards_GetPartnershipByBranchCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Rewards_GetPartnershipByBranchCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Customer_GetMemberCardNoCompletedEventHandler(object sender, Customer_GetMemberCardNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Customer_GetMemberCardNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Customer_GetMemberCardNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Customer_UpdateCardNoCompletedEventHandler(object sender, Customer_UpdateCardNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Customer_UpdateCardNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Customer_UpdateCardNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Branch_GetDetailsByBranchCodeCompletedEventHandler(object sender, Branch_GetDetailsByBranchCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Branch_GetDetailsByBranchCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Branch_GetDetailsByBranchCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Common_GetGenerateNewIDCompletedEventHandler(object sender, Common_GetGenerateNewIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Common_GetGenerateNewIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Common_GetGenerateNewIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Common_GenerateReturnCompletedEventHandler(object sender, Common_GenerateReturnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Common_GenerateReturnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Common_GenerateReturnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Common_GenerateReturnSubmitCompletedEventHandler(object sender, Common_GenerateReturnSubmitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Common_GenerateReturnSubmitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Common_GenerateReturnSubmitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Common_GetMessageCompletedEventHandler(object sender, Common_GetMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Common_GetMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Common_GetMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Common_GetModalMessageCompletedEventHandler(object sender, Common_GetModalMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Common_GetModalMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Common_GetModalMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Common_SendSMSCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Common_SendEmailCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591